<a href="https://colab.research.google.com/github/PrimorInfo/AulaInaugural/blob/main/Aula2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Dicionários

In [1]:
notas ={'portugues': 8, 'ingles': 7.4, 'matematica': 9}
notas

{'portugues': 8, 'ingles': 7.4, 'matematica': 9}

In [2]:
pessoa = {'nome': 'Joao', 'idade': 35, 'profissao': 'pintor'}
pessoa

{'nome': 'Joao', 'idade': 35, 'profissao': 'pintor'}

In [3]:
times = {1:'Flamengo', 2: 'São Paulo', 3: 'Grêmio'}
times

{1: 'Flamengo', 2: 'São Paulo', 3: 'Grêmio'}

>Selecionando Elementos

In [5]:
notas['matematica']

9

In [6]:
pessoa['nome']

'Joao'

In [7]:
times[2]

'São Paulo'

>Alterando Elementos

In [9]:
notas['matematica'] = 10
notas

{'portugues': 8, 'ingles': 7.4, 'matematica': 10}

In [12]:
times[2] = 'Palmeiras'
times

{1: 'Flamengo', 2: 'Palmeiras', 3: 'Grêmio'}

>Adicionando Elementos

In [13]:
notas['Geografia'] = 7.1
notas

{'portugues': 8, 'ingles': 7.4, 'matematica': 10, 'Geografia': 7.1}

In [14]:
times[85] = 'Vasco'
times

{1: 'Flamengo', 2: 'Palmeiras', 3: 'Grêmio', 85: 'Vasco'}

##If / Else

In [16]:
x = 1
y = 5

>Operadores Lógicos

In [17]:
x == 1

True

In [18]:
x == 2

False

In [19]:
x < 0

False

In [20]:
x >= 0

True

In [21]:
x != 0

True

In [25]:
(x > 0) and (y < 2)

False

In [26]:
(x > 0) or (y < 2)

True

>Identação Obrigatória

In [31]:
x = 5
if (x > 0):
  print('x é maior do que zero')
else:
  print('x é menor ou igual a zero')

x é maior do que zero


In [34]:
x = 0
if (x > 0):
  print('x é maior do que zero')
elif(x == 0):
  print('x é zero')
else:
  print('x é menor ou igual a zero')

x é zero


##For

In [50]:
contador = [0,1,2,3,4,5,6,7,8,9]
contador

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [51]:
for valor in contador:
  print(valor)

0
1
2
3
4
5
6
7
8
9


In [52]:
range?

In [55]:
for valor in range(10):
  print(valor)

0
1
2
3
4
5
6
7
8
9


In [56]:
for i in range(4,18,2):
  print(i)

4
6
8
10
12
14
16


In [59]:
cidades = ['São Paulo', 'Brasília', 'Curitiba']
cidades

['São Paulo', 'Brasília', 'Curitiba']

In [63]:
for cidade in cidades:
  print('Já morei em '+ cidade)

Já morei em São Paulo
Já morei em Brasília
Já morei em Curitiba


In [65]:
minha_lista = [1,2,3, 'cachorro', 'gato', 'papagaio']
minha_lista

[1, 2, 3, 'cachorro', 'gato', 'papagaio']

In [67]:
for cada_item in minha_lista:
  print(cada_item)

1
2
3
cachorro
gato
papagaio


##While

In [68]:
x = 0
while x < 5:
  print(x)
  x = x + 1

0
1
2
3
4


##List Comprehension

In [75]:
quadrados =[]
for numero in range(10):
  quadrados.append(numero**2)

quadrados

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

>Uma maneira mais concisa de criar listas

In [76]:
quad = [x**2 for x in range(10)]
quad

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

##Funções

>Função que não retorna valor

In [78]:
def exibir_mensagem(parametro):
  print('Mensagem >> ' + parametro)

In [79]:
exibir_mensagem('Olá!!!')

Mensagem >> Olá!!!


In [80]:
exibir_mensagem('Tudo bem?')

Mensagem >> Tudo bem?


In [83]:
def exibir_dados(nome, idade):
  print('Meu nome é {}'.format(nome))
  print('Tenho {} anos'.format(idade))

In [84]:
exibir_dados('Maria', 35)

Meu nome é Maria
Tenho 35 anos


>Função que retorna valor

In [85]:
def elevar_ao_quadrado(numero):
  return numero ** 2

In [86]:
elevar_ao_quadrado(2)

4

In [87]:
elevar_ao_quadrado(22)

484

##Bibliotecas

>Já instaladas no Ambiente (Google Colab)

In [88]:
import numpy

In [89]:
numpy.ones(5)

array([1., 1., 1., 1., 1.])

In [90]:
import numpy as np

In [92]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [93]:
from numpy import ones

In [94]:
ones(6)

array([1., 1., 1., 1., 1., 1.])

>Instalando Bibliotecas Externas (um exemplo abaixo)

In [ ]:
 !pip install yfinance

In [98]:
import yfinance as yf

In [ ]:
yf.download('^BVSp')